import type { Metadata } from "next";
import { Outfit, Space_Grotesk } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";

const geistOutfit = Outfit({
  variable: "--font-Outfit",
  subsets: ["latin"],
});

const geistGrotesk = Space_Grotesk({
  variable: "--font-Space-grotesk",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistOutfit.variable} ${geistGrotesk.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">

        <Navbar/>

        {children}

        </body>
    </html>
  );
}
